Batch Monitoring/src/objects/BulkAPIJob__c.object
<CustomObject>
    <description>This Object stores information about the Bulk API Jobs which is available in Bulk Data Load Jobs Standard Page</description>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BulkAPIJob</label>
    <nameField>
        <label>BulkAPIJob Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BulkAPIJobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Batch Monitoring/src/objects/BulkAPIJobBatches__c.object
<CustomObject>
    <description>This object stores all the batch details of Bulk API Jobs.</description>
    <fields>
        <fullName>BulkAPIJob_ID__c</fullName>
        <label>BulkAPIJob ID</label>
        <referenceTo>BulkAPIJob__c</referenceTo>
        <relationshipLabel>BulkAPIJobBatches</relationshipLabel>
        <relationshipName>BulkAPIJobBatches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <label>Created Date</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberOfRecordsFailed__c</fullName>
        <label>NumberOfRecordsFailed</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberOfRecordsProcessed__c</fullName>
        <label>NumberOfRecordsProcessed</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>BulkAPIJobBatches</label>
    <nameField>
        <label>BulkAPIJobBatches Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BulkAPIJobBatches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Batch Monitoring/src/objects/BulkJobsConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It is used to store endpoint URLs</description>
    <fields>
        <fullName>Failure_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failure Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Success_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Success Status</label>
        <type>Checkbox</type>
    </fields>
    <label>BulkJobsConfig</label>
</CustomObject>

Batch Monitoring/src/classes/BatchAutomationUtils.cls
/*################################################################################
Project Name: <Batch Monitoring Automation>
File : <BatchAutomationUtils>
version: <1.0>
Created by : <Infosys Technologies>
Created Date: 8/10/2016
Last Modified By:Jothi
Last Modified Date:8/11/2016
Description: Utils Class for common query results 

################################################################################*/
public class BatchAutomationUtils
{
    public static List<BulkAPIJobBatches__c> getBatchStatuslist()
    {
        List<BulkAPIJobBatches__c> batchList = new List<BulkAPIJobBatches__c>();
        BulkAPIAuthenticationConfig__c auth = new BulkAPIAuthenticationConfig__c();
        auth = getAuthenticationDetails();
        DateTime sentDate = auth.LastProcessedTime__c;        
        String query;
        if(BulkJobsConfig__c.getvalues('BatchMonitor').Failure_Status__c == true)       
        query = 'SELECT id,Name,BulkAPIJob_ID__c,State__c,Created_Date__c,NumberOfRecordsProcessed__c,NumberOfRecordsFailed__c,BulkAPIJob_ID__r.Name,BulkAPIJob_ID__r.Object__c,BulkAPIJob_ID__r.Operation__c FROM BulkAPIJobBatches__c WHERE createddate >:sentDate and NumberOfRecordsFailed__c !='+'\''+ 0 +'\'';        
        else if(BulkJobsConfig__c.getvalues('BatchMonitor').Success_Status__c == True)
        query = 'SELECT id,Name,BulkAPIJob_ID__c,State__c,Created_Date__c,NumberOfRecordsProcessed__c,NumberOfRecordsFailed__c,BulkAPIJob_ID__r.Name,BulkAPIJob_ID__r.Object__c,BulkAPIJob_ID__r.Operation__c FROM BulkAPIJobBatches__c WHERE createddate >:sentDate and NumberOfRecordsFailed__c= '+'\''+ 0+'\'';       
        try
        {
            if(query !=  null)
            batchList = Database.Query(query);
        }
        Catch(Exception e)
        {
        }
        return batchList;
    }
    public static id getEmailTemplate(String Name)
    {        
        return [select id, name from EmailTemplate where developername =: Name].id;   
    }
    public static BulkAPIAuthenticationConfig__c getAuthenticationDetails()
    {
        BulkAPIAuthenticationConfig__c authenticationKeys = [select ConsumerKey__c,ConsumerSecret__c,Username__c,Password__c,LastProcessedTime__c,LastHourlyProcessedTime__c from BulkAPIAuthenticationConfig__c where name ='BatchMonitor'];  
        return authenticationKeys;
       
    }
   
}