Batch Monitoring/src/objects/BulkAPIJob__c.object
<CustomObject>
    <description>This Object stores information about the Bulk API Jobs which is available in Bulk Data Load Jobs Standard Page</description>
    <label>BulkAPIJob</label>
    <nameField>
        <label>BulkAPIJob Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BulkAPIJobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Batch Monitoring/src/objects/BulkAPIJobBatches__c.object
<CustomObject>
    <description>This object stores all the batch details of Bulk API Jobs.</description>
    <fields>
        <fullName>APIActiveProcessingTime__c</fullName>
        <label>APIActiveProcessingTime</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ApexProcessingTime__c</fullName>
        <label>ApexProcessingTime</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <label>Created Date</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobId__c</fullName>
        <label>JobId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberOfRecordsFailed__c</fullName>
        <label>NumberOfRecordsFailed</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberOfRecordsProcessed__c</fullName>
        <label>NumberOfRecordsProcessed</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SystemModstamp__c</fullName>
        <label>SystemModstamp</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalProcessingTime__c</fullName>
        <label>TotalProcessingTime</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>BulkAPIJobBatches</label>
    <nameField>
        <label>BulkAPIJobBatches Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BulkAPIJobBatches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Batch Monitoring/src/objects/BulkJobsConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It is used to store endpoint URLs</description>
    <fields>
        <fullName>Namespace__c</fullName>
        <label>Namespace</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>BulkJobsConfig</label>
</CustomObject>

Batch Monitoring/src/classes/BatchAutomationXMLParser.cls
/*################################################################################
Project Name: <Batch Monitoring Automation>
File : <BatchAutomationXMLParser>
version: <1.0>
Created by : <Infosys Technologies>
Created Date: 9/01/2016
Last Modified By:
Last Modified Date:
Description:This class to parse Response XML. 
################################################################################*/

public class BatchAutomationXMLParser
{
    //Variable  Declaration
    public static list<BulkAPIJobBatches__c> batchList = new list<BulkAPIJobBatches__c>();      
    public static BulkAPIJobBatches__c batch;
    
    //This method is to parse response XML    
    public list<BulkAPIJobBatches__c> parseXML(string responseXml,string jobID)
    {
        DOM.Document xmlDOC = new DOM.Document();
        xmlDOC.load(responseXml);      
        DOM.XMLNode rootElement = xmlDOC.getRootElement();        
               
        for(DOM.XMLNode child:rootElement.getChildElements())      
        {             
            
            BulkAPIJobBatches__c b = loadChilds(child,jobId); 
            batchList.add(b);
               
        } 
        return batchList;
        
    }
    //Method to get APIVersion of the job
    public string getAPIVersion(string responseXml)
    {
        String nameSpace = BulkJobsConfig__c.getvalues('BatchMonitor').Namespace__c;       
        DOM.Document xmlDOC = new DOM.Document();
        xmlDOC.load(responseXml);      
        DOM.XMLNode rootElement = xmlDOC.getRootElement(); 
        string errorMessage = rootElement.getChildElement('exceptionMessage',nameSpace).gettext();            
        system.debug('print error message###'+errorMessage);
        string apiVersion;
        if(errorMessage != null)
        {
            errorMessage = errorMessage.trim();
            system.debug('###trimmed'+errorMessage.right(4));
            apiVersion = errorMessage.right(4);
        } 
        return apiVersion;        
    }
    // This method loads the child elements and Maps the corresponding fields
    public static BulkAPIJobBatches__c loadChilds(DOM.XMLNode xmlnode,String jobid)
    {                          
        BulkAPIJob__c job = new BulkAPIJob__c();
        String nameSpace = BulkJobsConfig__c.getvalues('BatchMonitor').Namespace__c;       
        batch = new BulkAPIJobBatches__c();      
        batch.JobId__c = jobid;
        batch.Name = xmlnode.getChildElement('id',nameSpace).gettext();
        batch.State__c= xmlnode.getChildElement('state',nameSpace).gettext();
        batch.Created_Date__c= xmlnode.getChildElement('createdDate',nameSpace).gettext();
        batch.NumberOfRecordsProcessed__c= xmlnode.getChildElement('numberRecordsProcessed',nameSpace).gettext();
        batch.NumberOfRecordsFailed__c= xmlnode.getChildElement('numberRecordsFailed',nameSpace).gettext();
        batch.SystemModstamp__c= xmlnode.getChildElement('systemModstamp',nameSpace).gettext();
        batch.TotalProcessingTime__c= xmlnode.getChildElement('totalProcessingTime',nameSpace).gettext();
        batch.APIActiveProcessingTime__c =xmlnode.getChildElement('apiActiveProcessingTime',nameSpace).gettext();
        batch.ApexProcessingTime__c=xmlnode.getChildElement('apexProcessingTime',nameSpace).gettext();                           
        return batch;
              
        
    }


}