Batch Monitoring/src/objects/BulkAPIJob__c.object
<CustomObject>
    <description>This Object stores information about the Bulk API Jobs which is available in Bulk Data Load Jobs Standard Page</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>BulkAPIJob</label>
    <nameField>
        <label>BulkAPIJob Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BulkAPIJobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Batch Monitoring/src/objects/BulkAPIJobBatches__c.object
<CustomObject>
    <description>This object stores all the batch details of Bulk API Jobs.</description>
    <fields>
        <fullName>BulkAPIJob_ID__c</fullName>
        <label>BulkAPIJob ID</label>
        <referenceTo>BulkAPIJob__c</referenceTo>
        <relationshipLabel>BulkAPIJobBatches</relationshipLabel>
        <relationshipName>BulkAPIJobBatches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>NumberOfRecordsFailed__c</fullName>
        <label>NumberOfRecordsFailed</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>BulkAPIJobBatches</label>
    <nameField>
        <label>BulkAPIJobBatches Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BulkAPIJobBatches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Batch Monitoring/src/objects/BulkJobsConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It is used to store endpoint URLs</description>
    <fields>
        <fullName>AuthenticationURL__c</fullName>
        <label>AuthenticationURL</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BulkAPIJobURL__c</fullName>
        <label>BulkAPIJobURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Notification__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Email Notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Failure_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failure Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Namespace__c</fullName>
        <label>Namespace</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SendToAddress__c</fullName>
        <label>SendToAddress</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Success_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Success Status</label>
        <type>Checkbox</type>
    </fields>
    <label>BulkJobsConfig</label>
</CustomObject>

Batch Monitoring/src/classes/BatchAutomation_DataFactory.cls
@isTest
public class BatchAutomation_DataFactory
{
    public static BulkAPIJob__c createBulkJob(String name)
    {
        BulkAPIJob__c bulkJob = new BulkAPIJob__c();    
        bulkJob.Name = name;
        //bulkJob.status__c= Status;
        return bulkJob;
    }
    public static BulkAPIJobBatches__c createBulkJobBatches(String jobId,String BatchId)
    {
        BulkAPIJobBatches__c batch = new BulkAPIJobBatches__c();    
        batch.Name = BatchId;
        batch.BulkAPIJob_ID__c = jobId;
        batch.NumberOfRecordsFailed__c = '12';
        //bulkJob.status__c= Status;
        return batch;
    }
    public static BulkJobsConfig__c createConfigRecord()
    {
        BulkJobsConfig__c bulkJobConfig = new BulkJobsConfig__c();
        bulkJobConfig.name = 'BatchMonitor';
        bulkJobConfig.BulkAPIJobURL__c = 'https://ap2.salesforce.com/750';       
        bulkJobConfig.AuthenticationURL__c ='https://login.salesforce.com/services/oauth2/token';
        bulkJobConfig.SendToAddress__c='test@gmail.com;test1@yahoo.com';
        bulkJobConfig.Namespace__c='http://www.force.com/2009/06/asyncapi/dataload';
        bulkJobConfig.Email_Notification__c = true;
        bulkJobConfig.Success_Status__c = False;
        bulkJobConfig.Failure_Status__c = true;  
        bulkJobConfig.SendToAddress__c  = '0054C000000YJotQAG';           
        return bulkJobConfig;
    }
    public static BulkAPIAuthenticationConfig__c createAuthenticationRecord(string name)
    {
        BulkAPIAuthenticationConfig__c auth = new BulkAPIAuthenticationConfig__c();
        auth.Name = name;      
        auth.consumerKey__c ='3MVG9AJuBE3rTYDhjPN.ghgfjhgjhjhj';
        auth.ConsumerSecret__c = '25657568678678546';
        auth.USERNAME__c = 'sampleUsername.toyota.com.amsinfy';
        auth.password__c ='dummypassword';        
        auth.LastProcessedTime__c = System.Now()-2;
        auth.LastHourlyProcessedTime__c = DateTime.Now()-2;
        return auth;
        
    }
    public static emailtemplate createEmailTemplate(string name)
    {
        emailtemplate temp = new emailtemplate();
        temp.Name = name;
        return temp;
    }
    
}